services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dropboxproject
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  dropbox-app:
    build: .
    container_name: dropbox-container
    ports:
      - "8090:8080"
    volumes:
      - app_data:/app/uploads
    environment:
      # MySQL Bağlantı Bilgileri
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/dropboxproject?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
      
      # JPA/Hibernate Ayarları
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      
      # Dosya yükleme ayarları
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 20MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 20MB
      APP_UPLOAD_DIR: /app/uploads

      # Email Bilgileri
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: javadosyapaylasimi@gmail.com
      SPRING_MAIL_PASSWORD: X5j13$#eCM1cG@Kdc

      # Spring Profil Ayarı
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local